### PR TITLE
switch to .NET7 (add support for ppc64le)

### PR DESCRIPTION
**Pull request by Sachin-Itagi**
Added .NET7 to the devspaces-udi Dockerfile 

.NET7 includes support for new architecture Power (ppc64le).

https://issues.redhat.com/browse/CRW-3512

### CODE REVIEW

**Comment by nickboldt** [comment]
Do we know what version is shown when you run `/usr/bin/dotnet` or `dotnet --info` ? Just curious which version becomes the default...

**Comment by ghatwala** [comment]
@nickboldt  - installed and checked below on IBM power 
```
# yum install -y dotnet dotnet-sdk-7.0
Updating Subscription Management repositories.
Red Hat CodeReady Linux Builder for RHEL 8 Power, little endian (RPMs)                                                75 kB/s | 4.5 kB     00:00
Red Hat Virtualization 4 Management Agents for RHEL 8 Power, little endian (RPMs)                                     69 kB/s | 4.0 kB     00:00
Package dotnet-7.0.100-1.el8_7.ppc64le is already installed.
Package dotnet-sdk-7.0-7.0.100-1.el8_7.ppc64le is already installed.
Dependencies resolved.
Nothing to do.
Complete!

```
checking ...
```
# /usr/bin/dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     rhel
 OS Version:  8
 OS Platform: Linux
 RID:         rhel.8-ppc64le
 Base Path:   /usr/lib64/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: ppc64le
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

# dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     rhel
 OS Version:  8
 OS Platform: Linux
 RID:         rhel.8-ppc64le
 Base Path:   /usr/lib64/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: ppc64le
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

**Review by svor — APPROVED** [review]
LGTM

**Comment by nickboldt** [comment]
I was asking what you get when all three are installed, but this is good enough :D 

Merging...

**Comment by ghatwala** [comment]
> I was asking what you get when all three are installed

for IBM power , we can install dotnet7 only :) , may be this needs to be tried ( 3.1 , 6.0, 7.0) on x86/RHEL nodes to confirm default dotnet version . Thanks for merging @nickboldt .

**Comment by omajid** [comment]
> Do we know what version is shown when you run `/usr/bin/dotnet` or `dotnet --info` ? Just curious which version becomes the default...

If I could borrow a python metaphor, `dotnet` includes features of `python3`, `python3.10`, `python3.11` and `venv`, all in one binary.

There isn't really a default, per se. `dotnet --info` will show *all* installed versions. The version selection is done in project configuration; if nothing is selected, the latest version is used to create projects.

For the .NET SDK, you can select the SDK version you want by specifying that in a `global.json` file in your project (otherwise it tries to use the latest SDK). For the Runtime, you can generally specify the runtime your code wants by using a `TargetFramework` in your project file. There's also options to make runtime selection more flexible - you can specify requirements like "use only .NET 6" or "use .NET 6 but .NET 7 is okay as a fallback too". 

More about this at: https://learn.microsoft.com/en-us/dotnet/core/versions/selection

**Pull request merged**
