### PR TITLE
Upgrade python to 3.11

### PR DESCRIPTION
**Pull request by svor**
Upgrades python from 3.9 to 3.11.x (3.11.2) version

**Related issue:** https://issues.redhat.com/browse/CRW-4944

Can be tested with quay.io/vsvydenk/udi:python11
or
You can start a  python workspace with an updated image by clicking:
[Contribute](https://devspaces.apps.sandbox-stage.gb17.p1.openshiftapps.com/dashboard/#/https://github.com/svor/python-hello-world/tree/ds-python11) 

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.11.13-14_11_57.webm](https://github.com/redhat-developer/devspaces-images/assets/1271546/9136aedb-27b6-4379-904f-11d54fb60f78)

### CODE REVIEW

**Review by nickboldt — APPROVED** [review]
LGTM, didn't build/test.

**Comment by AObuchow** [comment]
For some reason, brew builds using python 3.11 are currently failing to install it, e.g. [this one](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2777589):

```
2023-11-14 09:25:33,282 - atomic_reactor.tasks.binary_container_build - INFO - Complete.
2023-11-14 09:25:33,283 - atomic_reactor.tasks.binary_container_build - INFO - Unable to resolve argument python3.11
2023-11-14 09:25:33,283 - atomic_reactor.tasks.binary_container_build - INFO - Error: Problems in request:
2023-11-14 09:25:33,283 - atomic_reactor.tasks.binary_container_build - INFO - missing groups or modules: python3.11
```

**Comment by AObuchow** [comment]
The above-mentioned issue will be addressed in https://github.com/redhat-developer/devspaces-images/pull/525

**Comment by svor** [comment]
@AObuchow good catch. It seems the build is not failed but I see the errors.
we need to remove `python3.11` from line `dnf -y -q module reset container-tools maven nodejs python3.11 php; \`, because there are no modules for python 3.11. I've checked this in brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=57035330

@AObuchow  are you going to fix that in your PR or you want me to provide this fix?

**Pull request merged**
