### PR TITLE
Update to Traefik v2.9.6

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

### Reference issue
https://issues.redhat.com/browse/CRW-3606

### CODE REVIEW

**Comment by nickboldt** [comment]
Does the fact that upstream uses golang 1.19 mean we can't build this in a golang 1.18 environment?

https://github.com/traefik/traefik/blob/v2.9.6/go.mod#L3
https://github.com/traefik/traefik/blob/v2.9.6/exp.Dockerfile
vs.

https://github.com/redhat-developer/devspaces-images/blob/devspaces-3-rhel-8/devspaces-traefik/build/rhel.Dockerfile#L16

Looks like we're still using node 12:
https://github.com/traefik/traefik/blob/v2.9.6/exp.Dockerfile#L2
vs.
https://github.com/redhat-developer/devspaces-images/blob/devspaces-3-rhel-8/devspaces-traefik/build/rhel.Dockerfile#L13-L14

**Comment by nickboldt** [comment]
go 1.19 exists for centos 8 and 9, but is not yet available in ubi8/9 content sets:

* https://rpmfind.net/linux/rpm2html/search.php?query=golang
vs.
* https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1 (1.18)
* https://catalog.redhat.com/software/containers/ubi9/go-toolset/61e5c00b4ec9945c18787690?container-tabs=gti (1.18)

**Comment by nickboldt** [comment]
From Anatoli:
> The PR is postponed until we have go 1.19 on UBI.

**Comment by SDawley** [comment]
Closing since we've since moved past 2.9

**Pull request closed without merging**
